version: '2'
services:
    schoolregistration-app:
        image: schoolregistration
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://schoolregistration-mysql:3306/schoolregistration?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=schoolregistration-elasticsearch:9300
        ports:
            - 8080:8080
    schoolregistration-mysql:
        extends:
            file: mysql.yml
            service: schoolregistration-mysql
    schoolregistration-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: schoolregistration-elasticsearch
